// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8SNkmu-oCv7Q_Tt9zSkv0QGWad0h2iKU',
    appId: '1:1039198524016:web:d6000cc423897b7f815ab5',
    messagingSenderId: '1039198524016',
    projectId: 'fassum-app',
    authDomain: 'fassum-app.firebaseapp.com',
    databaseURL: 'https://fassum-app-default-rtdb.firebaseio.com',
    storageBucket: 'fassum-app.appspot.com',
    measurementId: 'G-PDQV27G2LM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuM96pPPPdTLAYDoq48UUbP1J79E5VpoM',
    appId: '1:1039198524016:android:f2d8b7855e772c84815ab5',
    messagingSenderId: '1039198524016',
    projectId: 'fassum-app',
    databaseURL: 'https://fassum-app-default-rtdb.firebaseio.com',
    storageBucket: 'fassum-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrdPieVDoieo_3hTLYDnbUqjZmBXm5Rw0',
    appId: '1:1039198524016:ios:62db972b36f01a0b815ab5',
    messagingSenderId: '1039198524016',
    projectId: 'fassum-app',
    databaseURL: 'https://fassum-app-default-rtdb.firebaseio.com',
    storageBucket: 'fassum-app.appspot.com',
    iosClientId: '1039198524016-tabb3912g88dicgf9nb279jeq0blrlq2.apps.googleusercontent.com',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrdPieVDoieo_3hTLYDnbUqjZmBXm5Rw0',
    appId: '1:1039198524016:ios:f3796f66d00dc363815ab5',
    messagingSenderId: '1039198524016',
    projectId: 'fassum-app',
    databaseURL: 'https://fassum-app-default-rtdb.firebaseio.com',
    storageBucket: 'fassum-app.appspot.com',
    iosClientId: '1039198524016-frdsmg61imesrj75oo74rc8t880pqg6n.apps.googleusercontent.com',
    iosBundleId: 'com.example.fasum.RunnerTests',
  );
}
